//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace TranslatorSolutionLib.XMLModels
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://locult.codeplex.com/TranslatorSolution.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://locult.codeplex.com/TranslatorSolution.xsd", IsNullable=false)]
    public partial class TranslatorSolution {
        
        private string nameField;
        
        private string commentField;
        
        private PROJECT_TAG[] projectField;
        
        private string versionField;
        
        /// <remarks/>
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return commentField;
            }
            set {
                commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Project")]
        public PROJECT_TAG[] Project {
            get {
                return projectField;
            }
            set {
                projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return versionField;
            }
            set {
                versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://locult.codeplex.com/TranslatorSolution.xsd")]
    public partial class PROJECT_TAG
    {
        
        private FILE_TAG sourceFileField;
        
        private FILE_TAG[] targetFilesField;
        
        /// <remarks/>
        public FILE_TAG SourceFile {
            get {
                return sourceFileField;
            }
            set {
                sourceFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetFiles")]
        public FILE_TAG[] TargetFiles {
            get {
                return targetFilesField;
            }
            set {
                targetFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://locult.codeplex.com/TranslatorSolution.xsd")]
    public partial class FILE_TAG
    {
        
        private string pathField;
        
        private string typeField;
        
        private string commentField;
        
        /// <remarks/>
        public string Path {
            get {
                return pathField;
            }
            set {
                pathField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return typeField;
            }
            set {
                typeField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return commentField;
            }
            set {
                commentField = value;
            }
        }
    }
}
