//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocultApp.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocultApp.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access file : {0}..
        /// </summary>
        public static string CantAccessFile_Error_Text {
            get {
                return ResourceManager.GetString("CantAccessFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading log file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string ParseLogFile_Error_Text {
            get {
                return ResourceManager.GetString("ParseLogFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file....
        /// </summary>
        public static string ParseLogFile_Error_Title {
            get {
                return ResourceManager.GetString("ParseLogFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string STR_ABOUT_Copyright {
            get {
                return ResourceManager.GetString("STR_ABOUT_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string STR_ABOUT_Link {
            get {
                return ResourceManager.GetString("STR_ABOUT_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string STR_ABOUT_Modules {
            get {
                return ResourceManager.GetString("STR_ABOUT_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string STR_About_SETTINGS_Caption {
            get {
                return ResourceManager.GetString("STR_About_SETTINGS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string STR_ABOUT_Version {
            get {
                return ResourceManager.GetString("STR_ABOUT_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string STR_APPLY_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("STR_APPLY_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes for the following files?.
        /// </summary>
        public static string STR_ASK_TO_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("STR_ASK_TO_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution task processing is blocked by another task &apos;{0}&apos;.
        /// </summary>
        public static string STR_BLOCKED_SOLUTION_TASK {
            get {
                return ResourceManager.GetString("STR_BLOCKED_SOLUTION_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the list of preferred folder locations for this application..
        /// </summary>
        public static string STR_BOOKMARK_LIST_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_BOOKMARK_LIST_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string STR_BOOKMARKS_OPTION_CAPTION {
            get {
                return ResourceManager.GetString("STR_BOOKMARKS_OPTION_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a set of frequently used folders and access them via shortcut in the application.
        /// </summary>
        public static string STR_BOOKMARKS_OPTION_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_BOOKMARKS_OPTION_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A load operation is currently in progress. Would you like to cancel the current process?.
        /// </summary>
        public static string STR_CANCEL_LOAD_MESSAGE {
            get {
                return ResourceManager.GetString("STR_CANCEL_LOAD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A save operation is currently in progress. Would you like to cancel the current process?.
        /// </summary>
        public static string STR_CANCEL_SAVE_MESSAGE {
            get {
                return ResourceManager.GetString("STR_CANCEL_SAVE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string STR_CAPTION_ADD {
            get {
                return ResourceManager.GetString("STR_CAPTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string STR_CAPTION_ADD_Files {
            get {
                return ResourceManager.GetString("STR_CAPTION_ADD_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string STR_CAPTION_CANCEL {
            get {
                return ResourceManager.GetString("STR_CAPTION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string STR_CAPTION_EXIT {
            get {
                return ResourceManager.GetString("STR_CAPTION_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string STR_CAPTION_NEW_BUTTON {
            get {
                return ResourceManager.GetString("STR_CAPTION_NEW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new solution for this application.
        /// </summary>
        public static string STR_CAPTION_NEW_BUTTON_TT {
            get {
                return ResourceManager.GetString("STR_CAPTION_NEW_BUTTON_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string STR_CAPTION_OPEN_BUTTON {
            get {
                return ResourceManager.GetString("STR_CAPTION_OPEN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the solution data into the application.
        /// </summary>
        public static string STR_CAPTION_OPEN_BUTTON_TT {
            get {
                return ResourceManager.GetString("STR_CAPTION_OPEN_BUTTON_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string STR_CAPTION_REMOVE {
            get {
                return ResourceManager.GetString("STR_CAPTION_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string STR_CAPTION_SAVE {
            get {
                return ResourceManager.GetString("STR_CAPTION_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Solution.
        /// </summary>
        public static string STR_CAPTION_SAVE_SOLUTION {
            get {
                return ResourceManager.GetString("STR_CAPTION_SAVE_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string STR_CAPTION_SETTINGS {
            get {
                return ResourceManager.GetString("STR_CAPTION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string STR_CAPTION_SHOW_STARTPAGE {
            get {
                return ResourceManager.GetString("STR_CAPTION_SHOW_STARTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete {0} entries?.
        /// </summary>
        public static string STR_CONFIRM_DELETING_ENTRIES {
            get {
                return ResourceManager.GetString("STR_CONFIRM_DELETING_ENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry?.
        /// </summary>
        public static string STR_CONFIRM_DELETING_ENTRIES_CAPTION {
            get {
                return ResourceManager.GetString("STR_CONFIRM_DELETING_ENTRIES_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string STR_CREATED_WITH_DATE_TIME_APPENDED {
            get {
                return ResourceManager.GetString("STR_CREATED_WITH_DATE_TIME_APPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        public static string STR_CURRENT_APP_LANG_CAPTION {
            get {
                return ResourceManager.GetString("STR_CURRENT_APP_LANG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your prevered application language.
        /// </summary>
        public static string STR_CURRENT_APP_LANG_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_CURRENT_APP_LANG_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Source Language.
        /// </summary>
        public static string STR_DefaultSourceLanguage_CAPTION {
            get {
                return ResourceManager.GetString("STR_DefaultSourceLanguage_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your default source language to translate from..
        /// </summary>
        public static string STR_DefaultSourceLanguage_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_DefaultSourceLanguage_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Target Language.
        /// </summary>
        public static string STR_DefaultTargetLanguage_CAPTION {
            get {
                return ResourceManager.GetString("STR_DefaultTargetLanguage_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your default target language to translate from..
        /// </summary>
        public static string STR_DefaultTargetLanguage_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_DefaultTargetLanguage_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory: &apos;{0}&apos;\nfor the new solution cannot be accessed..
        /// </summary>
        public static string STR_ERROR_ACCESSING_DIRECTORY {
            get {
                return ResourceManager.GetString("STR_ERROR_ACCESSING_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file: &apos;{0}&apos;\ncannot be accessed..
        /// </summary>
        public static string STR_ERROR_ACCESSING_FILE {
            get {
                return ResourceManager.GetString("STR_ERROR_ACCESSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file:\n&apos;{0}&apos;\nalready exists. Use &apos;Open Solution&apos; to edit it..
        /// </summary>
        public static string STR_ERROR_ACCESSING_FILE_CREATE_WOULD_Overwrite {
            get {
                return ResourceManager.GetString("STR_ERROR_ACCESSING_FILE_CREATE_WOULD_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string STR_ERROR_CODE {
            get {
                return ResourceManager.GetString("STR_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference to:\n&apos;{0}&apos;\nis a dublicate in source and target..
        /// </summary>
        public static string STR_ERROR_DUPLICATE_REFERENCE {
            get {
                return ResourceManager.GetString("STR_ERROR_DUPLICATE_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting a target value comment requires a translation to be present..
        /// </summary>
        public static string STR_ERROR_SOURCE_COMMENT_WITHOUT_TRANSLATION {
            get {
                return ResourceManager.GetString("STR_ERROR_SOURCE_COMMENT_WITHOUT_TRANSLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting a source value comment requires a translation to be present..
        /// </summary>
        public static string STR_ERROR_TARGET_COMMENT_WITHOUT_TRANSLATION {
            get {
                return ResourceManager.GetString("STR_ERROR_TARGET_COMMENT_WITHOUT_TRANSLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting solution task processing failed: &apos;{0}&apos;.
        /// </summary>
        public static string STR_FAILED_RESET_OF_SOLUTION_TASK {
            get {
                return ResourceManager.GetString("STR_FAILED_RESET_OF_SOLUTION_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string STR_FileType_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Resource Files (*.resx)|*.resx.
        /// </summary>
        public static string STR_FileType_FileFilter_resx {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_resx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string STR_GENERAL_Add {
            get {
                return ResourceManager.GetString("STR_GENERAL_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string STR_General_Caption {
            get {
                return ResourceManager.GetString("STR_General_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string STR_GENERAL_DOWN {
            get {
                return ResourceManager.GetString("STR_GENERAL_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string STR_GENERAL_Remove {
            get {
                return ResourceManager.GetString("STR_GENERAL_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string STR_GENERAL_UP {
            get {
                return ResourceManager.GetString("STR_GENERAL_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid contains alternating colored rows.
        /// </summary>
        public static string STR_GridColorOptions {
            get {
                return ResourceManager.GetString("STR_GridColorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternating Color.
        /// </summary>
        public static string STR_GridColorOptions_AlternatingColor {
            get {
                return ResourceManager.GetString("STR_GridColorOptions_AlternatingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Solution.
        /// </summary>
        public static string STR_HEADER_NewSolution {
            get {
                return ResourceManager.GetString("STR_HEADER_NewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution.
        /// </summary>
        public static string STR_HEADER_OpenSolution {
            get {
                return ResourceManager.GetString("STR_HEADER_OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string STR_HEADER_Project {
            get {
                return ResourceManager.GetString("STR_HEADER_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string STR_HEADER_Solution {
            get {
                return ResourceManager.GetString("STR_HEADER_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Files.
        /// </summary>
        public static string STR_HEADER_TargetFiles {
            get {
                return ResourceManager.GetString("STR_HEADER_TargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size.
        /// </summary>
        public static string STR_ICON_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred icon size to match your screen resolution..
        /// </summary>
        public static string STR_ICON_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string STR_KEY_GRIDCOLUMN_HEADER {
            get {
                return ResourceManager.GetString("STR_KEY_GRIDCOLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string STR_LABEL_Comment {
            get {
                return ResourceManager.GetString("STR_LABEL_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details.
        /// </summary>
        public static string STR_LABEL_Error_Details {
            get {
                return ResourceManager.GetString("STR_LABEL_Error_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string STR_LABEL_FILES {
            get {
                return ResourceManager.GetString("STR_LABEL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string STR_LABEL_FOLDER_SELECTION {
            get {
                return ResourceManager.GetString("STR_LABEL_FOLDER_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string STR_LABEL_Location {
            get {
                return ResourceManager.GetString("STR_LABEL_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string STR_LABEL_Name {
            get {
                return ResourceManager.GetString("STR_LABEL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string STR_LABEL_PATH {
            get {
                return ResourceManager.GetString("STR_LABEL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Solutions.
        /// </summary>
        public static string STR_LABEL_RECENT_SOLUTION_ITEMS {
            get {
                return ResourceManager.GetString("STR_LABEL_RECENT_SOLUTION_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Directory.
        /// </summary>
        public static string STR_LABEL_SOLUTION_LOCATION {
            get {
                return ResourceManager.GetString("STR_LABEL_SOLUTION_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        public static string STR_LABEL_SourceFile {
            get {
                return ResourceManager.GetString("STR_LABEL_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File Directory.
        /// </summary>
        public static string STR_LABEL_SourceFileDirectory {
            get {
                return ResourceManager.GetString("STR_LABEL_SourceFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to leave settings without saving changes?.
        /// </summary>
        public static string STR_LEAVE_SETTINGS_WITHOUT_SAVING_CHANGES {
            get {
                return ResourceManager.GetString("STR_LEAVE_SETTINGS_WITHOUT_SAVING_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving without saving changes?.
        /// </summary>
        public static string STR_LEAVE_SETTINGS_WITHOUT_SAVING_CHANGES_TT {
            get {
                return ResourceManager.GetString("STR_LEAVE_SETTINGS_WITHOUT_SAVING_CHANGES_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator.
        /// </summary>
        public static string STR_MS_Translate_Caption {
            get {
                return ResourceManager.GetString("STR_MS_Translate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string STR_MS_TRANSLATE_PASSWD_CAPTION {
            get {
                return ResourceManager.GetString("STR_MS_TRANSLATE_PASSWD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string STR_MS_TRANSLATE_URI_CAPTION {
            get {
                return ResourceManager.GetString("STR_MS_TRANSLATE_URI_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string STR_MS_TRANSLATE_USER_CAPTION {
            get {
                return ResourceManager.GetString("STR_MS_TRANSLATE_USER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem has occurred while saving the file..
        /// </summary>
        public static string STR_MSG_ErrorSavingFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos;\nhas occurred while saving a file..
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingAFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos;\nhas occurred while saving the file\n:&apos;{1}&apos;.
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingFileX {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string STR_MSG_UnknownError_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in shut-down process..
        /// </summary>
        public static string STR_MSG_UnknownError_InShutDownProcess {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InShutDownProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings for New Solution.
        /// </summary>
        public static string STR_NewDefaultSolutionOptions_Caption {
            get {
                return ResourceManager.GetString("STR_NewDefaultSolutionOptions_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Settings.
        /// </summary>
        public static string STR_PROGRAM_SETTINGS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_PROGRAM_SETTINGS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to customize the setup of this program..
        /// </summary>
        public static string STR_PROGRAM_SETTINGS_PAGE_TITLE_TT {
            get {
                return ResourceManager.GetString("STR_PROGRAM_SETTINGS_PAGE_TITLE_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload files when application re-starts.
        /// </summary>
        public static string STR_ReloadFilesOnStartUp_CAPTION {
            get {
                return ResourceManager.GetString("STR_ReloadFilesOnStartUp_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string STR_SELECT_A_FOLDER {
            get {
                return ResourceManager.GetString("STR_SELECT_A_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Language.
        /// </summary>
        public static string STR_SourceLanguage_GridColumn_Header {
            get {
                return ResourceManager.GetString("STR_SourceLanguage_GridColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string STR_START_PAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_START_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to create a new solution with a translation project or load an existing solution..
        /// </summary>
        public static string STR_START_PAGE_TITLE_TT {
            get {
                return ResourceManager.GetString("STR_START_PAGE_TITLE_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string STR_State {
            get {
                return ResourceManager.GetString("STR_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        public static string STR_TargetLanguage_GridColumn_Header {
            get {
                return ResourceManager.GetString("STR_TargetLanguage_GridColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string STR_Translate {
            get {
                return ResourceManager.GetString("STR_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string STR_Translate_ContextMenu_Caption {
            get {
                return ResourceManager.GetString("STR_Translate_ContextMenu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string STR_Translate_FromSourceTo_Target {
            get {
                return ResourceManager.GetString("STR_Translate_FromSourceTo_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string STR_Translate_FromTargetTo_Source {
            get {
                return ResourceManager.GetString("STR_Translate_FromTargetTo_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string STR_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("STR_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string STR_Unknown_Error {
            get {
                return ResourceManager.GetString("STR_Unknown_Error", resourceCulture);
            }
        }
    }
}
