//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocultMetro.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocultMetro_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocultMetro_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocultMetro.Local.LocultMetro_Strings", typeof(LocultMetro_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string STR_ACCENT_LABEL {
            get {
                return ResourceManager.GetString("STR_ACCENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color for highlighting items with your preferred color..
        /// </summary>
        public static string STR_ACCENT_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_ACCENT_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string STR_AccentColor {
            get {
                return ResourceManager.GetString("STR_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the accent color with your favorite color and use it for highlighting in this application..
        /// </summary>
        public static string STR_AccentColor_TT {
            get {
                return ResourceManager.GetString("STR_AccentColor_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternating grid color.
        /// </summary>
        public static string STR_ALTERNATE_GRID_COLOR {
            get {
                return ResourceManager.GetString("STR_ALTERNATE_GRID_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string STR_Appearance_SETTINGS_Caption {
            get {
                return ResourceManager.GetString("STR_Appearance_SETTINGS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string STR_APPEARANCE_THEME {
            get {
                return ResourceManager.GetString("STR_APPEARANCE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string STR_DARK_THEME {
            get {
                return ResourceManager.GetString("STR_DARK_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Font Size.
        /// </summary>
        public static string STR_FIXED_FONT_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_FIXED_FONT_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred fixed font size to match your screen resolution..
        /// </summary>
        public static string STR_FIXED_FONT_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_FIXED_FONT_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string STR_FONT_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_FONT_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred font size to match your screen resolution..
        /// </summary>
        public static string STR_FONT_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_FONT_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size.
        /// </summary>
        public static string STR_ICON_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred icon size to match your screen resolution..
        /// </summary>
        public static string STR_ICON_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate grid color.
        /// </summary>
        public static string STR_IS_ALTERNATE_GRID_COLOR_SET {
            get {
                return ResourceManager.GetString("STR_IS_ALTERNATE_GRID_COLOR_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string STR_LIGHT_THEME {
            get {
                return ResourceManager.GetString("STR_LIGHT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string STR_Pallette {
            get {
                return ResourceManager.GetString("STR_Pallette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select palette of pre-selected colors..
        /// </summary>
        public static string STR_Pallette_TT {
            get {
                return ResourceManager.GetString("STR_Pallette_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string STR_Theme {
            get {
                return ResourceManager.GetString("STR_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a dark or light application theme to adjust the skin to your preference and light conditions..
        /// </summary>
        public static string STR_Theme_TT {
            get {
                return ResourceManager.GetString("STR_Theme_TT", resourceCulture);
            }
        }
    }
}
